name: Deploy Application

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
  workflow_dispatch:

# Kill the workflow if the PR is updated with a new commit. Pushes to main will run sequentially.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  call-helm-deploy-workflow:
    name: Build and Deploy Application
    uses: lockerstock/github-actions/.github/workflows/reusable-helm-deploy.yaml@main
    secrets:
      GHA_ACCESS_TOKEN: ${{ secrets.GHA_ACCESS_TOKEN }}
