name: Pull Request Verification

on:
  pull_request:

# Kill the workflow if the PR is updated with a new commit
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-verify-go-microservice-workflow:
    name: Verify Go Microservice
    uses: lockerstock/github-actions/.github/workflows/reusable-verify-go-microservice.yaml@main
    secrets:
      GHA_ACCESS_USER: ${{ secrets.GHA_ACCESS_USER }}
      GHA_ACCESS_TOKEN: ${{ secrets.GHA_ACCESS_TOKEN }}
      BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
