name: Create feature branch Namespace
description: Creates a feature branch Namespace with proper labels to allow replication of resources

inputs:
  token:
    description: GITHUB_TOKEN to access the GitHub API if the repository is private
    required: false

  namespace:
    description: 'Namespace to deploy Helm chart. If not provided, will be calculated from action trigger'
    required: false

outputs:
  namespace:
    description: Prepared namespace
    value: ${{ steps.namespace.outputs.name }}

runs:
  using: composite
  steps:
    - name: Get Namespace
      id: namespace
      uses: lockerstock/github-actions/get-namespace@main
      with:
        token: ${{ inputs.token }}
        namespace: ${{ inputs.namespace }}
        get_namespace: 'true'

    - name: Create Feature Namespace
      if: steps.namespace.outputs.exists != 'true'
      run: cat feature.namespace.yaml | envsubst | kubectl apply -f -
      env:
        NAMESPACE: ${{ steps.namespace.outputs.name }}
        REF_NAME: ${{ steps.namespace.outputs.ref }}
      working-directory: ${{ github.action_path }}/k8s
      shell: bash

    - name: Append service label
      if: steps.namespace.outputs.exists == 'true'
      run: |
        if [[ $(kubectl get namespace -l ${{ github.repository_owner }}/feature-branch==${{ steps.namespace.outputs.name }} -o name) ]]; then
          kubectl label namespace ${{ steps.namespace.outputs.name }} ${{ github.repository }}=''
        fi
      working-directory: ${{ github.action_path }}/k8s
      shell: bash
