name: Publish Nginx Image

on:
  workflow_dispatch:
    inputs:
      tag:
        default: 'latest'

jobs:
  push_docker_image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/lockerstock/github-actions/nginx:${{ inputs.tag }}
          platforms: linux/amd64
          file: .github/config/Dockerfile.nginx
