name: Deploy Kubernetes Application

on:
  workflow_call:
    secrets:
      GHA_ACCESS_USER:
        required: true
      GHA_ACCESS_TOKEN:
        required: true
      BUF_USER:
        required: true
      BUF_TOKEN:
        required: true

jobs:
  push_docker_image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write
      deployments: write

    outputs:
      image_tag: ${{ steps.docker.outputs.image_tag }}
      deployment_id: ${{ steps.deployment.outputs.deployment_id }}

    steps:
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Docker Tags
        id: docker
        uses: lockerstock/github-actions/get-docker-tags@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Start Deployment
        id: deployment
        uses: lockerstock/github-actions/deployment-status@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          step: start
          environment: ${{ steps.docker.outputs.environment }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.docker.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          labels: |
            "org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}"
            "org.opencontainers.image.authors=${{ github.repository_owner }},${{ github.actor }}"
            "org.opencontainers.image.version=${{ steps.docker.outputs.image_tag }}"
            "org.opencontainers.image.ref.name=${{ github.head_ref || github.ref_name }}"
            "org.opencontainers.image.environment=${{ steps.docker.outputs.environment }}"
            "org.opencontainers.image.sha=${{ github.sha }}"
          build-args: |
            RELEASE_VERSION=${{ steps.docker.outputs.image_tag }}
            ACTOR=${{ secrets.GHA_ACCESS_USER }}
            ACCESS_TOKEN=${{ secrets.GHA_ACCESS_TOKEN }}
            BUF_USER=${{ secrets.BUF_USER }}
            BUF_TOKEN=${{ secrets.BUF_TOKEN }}

  deploy:
    name: Deploy Helm Chart
    runs-on: self-hosted
    needs:
      - push_docker_image

    permissions:
      contents: write
      id-token: write
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Helm deploy
        id: deploy
        uses: lockerstock/github-actions/deploy-helm@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image_tag: ${{ needs.push_docker_image.outputs.image_tag }}
          chart_path: deployments/helm/${{ github.event.repository.name }}

      - name: Finish Deployment
        uses: lockerstock/github-actions/deployment-status@main
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deployment_id: ${{ needs.push_docker_image.outputs.deployment_id }}
          step: finish
          env_url: https://${{ steps.deploy.outputs.hostname }}
          environment: ${{ steps.deploy.outputs.environment }}
          auto_inactive: true
