name: Cleanup Repository Resources

on:
  workflow_call:
    inputs:
      skip_deployment_cleanup:
        description: Boolean flag to skip the deployment-cleanup job. Should be used if the repository does not create deployments.
        type: boolean
        required: false
        default: false

      skip_ghcr_cleanup:
        description: Boolean flag to skip the ghcr-cleanup job. Should be used if the repository does not publish a package.
        type: boolean
        required: false
        default: false

jobs:
  deployment-cleanup:
    if: ${{ !inputs.skip_deployment_cleanup }}
    runs-on: ubuntu-latest
    name: Cleanup Inactive Deployments

    strategy:
      matrix:
        environment:
          - development
          - staging
          - production

    steps:
      - uses: lockerstock/github-actions/delete-inactive-deployments@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: ${{ matrix.environment }}

  ghcr-cleanup:
    if: ${{ !inputs.skip_ghcr_cleanup }}
    runs-on: ubuntu-latest
    name: Cleanup GitHub Container Registry

    permissions:
      contents: read
      packages: write

    steps:
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: lockerstock/github-actions/cleanup-ghcr@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep_git_tags: true
          duration_to_keep: '30d'
          tags_to_keep: |
            staging
            latest
