name: Test git-tag-exists
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'git-tag-exists/**/*'
      - '.github/workflows/test-git-tag-exists.yaml'

jobs:
  test-git-tag-exists:
    name: Test get tag exists
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Git Tag Exists
        id: exists
        uses: ./git-tag-exists
        with:
          tag: add-release-notes

      - name: 'Existing tag: ${{ steps.exists.outputs.exists }}'
        run: echo "${{ steps.exists.outputs.exists }}"

      - name: Git Tag Does Not Exist
        id: does-not-exist
        uses: ./git-tag-exists
        with:
          tag: does-not-exist

      - name: 'Non-existing tag: ${{ steps.does-not-exist.outputs.exists }}'
        run: echo "${{ steps.does-not-exist.outputs.exists }}"
