name: Test deploy-helm
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'deploy-helm/**/*'
      - '.github/workflows/test-deploy-helm.yaml'

jobs:
  test-deploy-helm:
    name: Test Helm deploy
    runs-on: [self-hosted, k8s, development]

    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Helm deploy
        id: deploy
        uses: ./deploy-helm
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          chart_path: deploy-helm/charts/example

      - name: 'Namespace: ${{ steps.deploy.outputs.namespace }}'
        run: echo "${{ steps.deploy.outputs.namespace }}"

      - name: 'Chart Version: ${{ steps.deploy.outputs.chart_version }}'
        run: echo "${{ steps.deploy.outputs.chart_version }}"

      - name: Helm deploy from OCI registry
        id: oci-deploy
        uses: ./deploy-helm
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          chart_path: deploy-helm/charts/oci-example

      - name: 'OCI Registry Chart Version: ${{ steps.oci-deploy.outputs.chart_version }}'
        run: echo "${{ steps.oci-deploy.outputs.chart_version }}"

      - name: Helm deploy from repository
        id: repo-deploy
        uses: ./deploy-helm
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          chart_path: deploy-helm/charts/repo-example

      - name: 'Repository Chart Version: ${{ steps.repo-deploy.outputs.chart_version }}'
        run: echo "${{ steps.repo-deploy.outputs.chart_version }}"
