name: Test get-package-version
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'get-package-version/**/*'
      - '.github/workflows/test-get-package-version.yaml'

jobs:
  test-get-package-version:
    name: Test get package version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Latest Package Version
        id: existing
        uses: ./get-package-version
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package_name: github-actions/nginx
          package_version_constraint: latest
          timestamp_constraint: ${{ github.ref_type == 'tag' && github.event.head_commit.timestamp }}

      - name: 'Latest Package Results'
        run: |
          if [[ "${{ steps.existing.outputs.package_exists }}" != true || "${{ steps.existing.outputs.version_exists }}" != true ]]; then
            echo "::error::Invalid results for existing image and version"
            echo "Package Exists ${{ steps.existing.outputs.package_exists }}"
            echo "Version Exists ${{ steps.existing.outputs.version_exists }}"
            exit 1
          else 
            echo "Version: ${{ steps.existing.outputs.version }}"
          fi

      - name: Get Constrained Package Version
        id: constrained
        uses: ./get-package-version
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package_name: github-actions/nginx
          package_version_constraint: '>=0.1.0 <1'

      - name: 'Constrained Version Results'
        run: |
          if [[ "${{ steps.constrained.outputs.package_exists }}" != true || "${{ steps.constrained.outputs.version_exists }}" != true ]]; then
            echo "::error::Invalid results for constrained version"
            echo "Package Exists ${{ steps.constrained.outputs.package_exists }}"
            echo "Version Exists ${{ steps.constrained.outputs.version_exists }}"
            exit 1
          else 
            echo "Version: ${{ steps.constrained.outputs.version }}"
          fi
