name: Test deploy-helm
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'deploy-helm/**/*'
      - '.github/workflows/test-deploy-helm.yaml'

jobs:
  test-deploy-helm:
    name: Test Helm deploy
    runs-on: [self-hosted, k8s, development]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Helm deploy
        id: deploy
        uses: ./deploy-helm
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          chart_path: deploy-helm/charts/example

      - name: 'Namespace: ${{ steps.deploy.outputs.namespace }}'
        run: echo "${{ steps.deploy.outputs.namespace }}"

      - name: 'Chart Version: ${{ steps.deploy.outputs.chart_version }}'
        run: echo "${{ steps.deploy.outputs.chart_version }}"

      - name: Helm deploy from remote
        id: source-deploy
        uses: ./deploy-helm
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          chart_path: deploy-helm/charts/source-example

      - name: 'Remote Chart Version: ${{ steps.source-deploy.outputs.chart_version }}'
        run: echo "${{ steps.source-deploy.outputs.chart_version }}"
